export const FETCH_LIST_FILM_START = 'FETCH_LIST_FILM_START';
export const FETCH_LIST_FILM_SUCCESS = 'FETCH_LIST_FILM_SUCCESS';
export const FETCH_LIST_FILM_FAIL = 'FETCH_LIST_FILM_FAIL';
export const FETCH_LIST_SELECTED_FILM_START = 'FETCH_LIST_SELECTED_FILM_START';
export const FETCH_LIST_SELECTED_FILM_SUCCESS =
  'FETCH_LIST_SELECTED_FILM_SUCCESS';
export const FETCH_LIST_SELECTED_FILM_FAIL = 'FETCH_LIST_SELECTED_FILM_FAIL';
